export const cartContent = {
  bag: {
    metadata: {
      title: "Bag | Neonfold",
      description: "Review selected styles before checkout.",
    },
    eyebrow: "Your bag",
    title: "Bag",
    itemSingular: "item",
    itemPlural: "items",
    openLabel: "Open bag",
    closeLabel: "Close bag",
    updateError: "Bag could not be updated. Try again.",
    removeError: "Bag item could not be removed. Try again.",
    removeAction: "Remove",
    subtotalLabel: "Subtotal",
    shippingLabel: "Shipping",
    shippingPendingLabel: "Calculated later",
    totalLabel: "Total",
    checkoutAction: "Checkout",
    checkoutFullAction: "Continue to checkout",
    viewFullAction: "View full bag",
    summaryTitle: "Order summary",
    quantityPrefix: "Qty",
    decreaseQuantityPrefix: "Decrease",
    increaseQuantityPrefix: "Increase",
    quantitySuffix: "quantity",
    addedToastLabel: "Added to bag",
    dismissAddedToastLabel: "Dismiss add to bag message",
    summaryNote:
      "Add delivery details, choose shipping, then continue to payment.",
    emptyTitle: "Your bag is empty.",
    emptyDrawerTitle: "Your bag is empty",
    emptyDescription: "Choose a style and size to begin your order.",
    emptyPageDescription:
      "Start with the latest dresses, co-ords, and occasion pieces.",
    emptyAction: "Shop new arrivals",
  },
  addToBag: {
    colorLabel: "Color",
    sizeLabel: "Size",
    sizeChartAction: "Size chart",
    sizeHelpPrefix: "Select an available size for",
    quantityLabel: "Quantity",
    decreaseQuantityLabel: "Decrease quantity",
    increaseQuantityLabel: "Increase quantity",
    pendingLabel: "Adding...",
    submitLabel: "Add to bag",
    stickyPendingLabel: "Adding",
    stickySubmitLabel: "Add",
    messages: {
      missingSize: "Select a size before adding this item.",
      invalidQuantity: "Choose a quantity between 1 and 9.",
      added: "Added to bag.",
      error: "This item could not be added. Try again.",
    },
  },
} as const;
