export const catalogContent = {
  shop: {
    metadata: {
      title: "Shop New Arrivals | Neonfold",
      description:
        "Shop dresses, co-ords, tops, and occasionwear from Neonfold.",
    },
    eyebrow: "New arrivals",
    title: "Shop new arrivals.",
    description:
      "Dresses, co-ords, and sharper tops for dinners, wedding functions, launches, and weekends that need more polish.",
    allCategoryLabel: "All",
    categoryNavigationLabel: "Shop categories",
    countLabel: "styles",
    emptyTitle: "The shop is being prepared.",
    emptyDescription:
      "New arrivals will appear here as soon as they are available.",
    valueStrip: [
      {
        title: "Size notes before checkout.",
        text: "Fit and measurements are shown before you choose a size.",
      },
      {
        title: "Prepaid checkout.",
        text: "Pay securely after your address and delivery option are confirmed.",
      },
      {
        title: "India shipping.",
        text: "Delivery and return details are easy to find before purchase.",
      },
    ],
  },
  collection: {
    fallbackDescription: "Available styles from the current collection.",
    metadataDescriptionPrefix: "Shop",
    emptyTitle: "This collection is coming soon.",
    emptyDescription:
      "Styles from this collection will appear here as soon as they are available.",
    allProductsAction: "View all",
    countLabel: "styles",
  },
  productListing: {
    allCategoryLabel: "All",
    categoryNavigationLabel: "Shop categories",
    applyFiltersLabel: "Apply",
    clearFiltersLabel: "Clear all",
    filterPanelTitle: "Filters",
    filterPanelDescription: "Choose size, color, price, and sort options.",
    openFiltersLabel: "Open filters",
    closeFiltersLabel: "Close filters",
    selectedFiltersLabel: "Selected filters",
    filtersUpdateLabel: "Use filters to refine products",
    countSingular: "style",
    countPlural: "styles",
    filters: {
      sizeLabel: "Size",
      allSizesLabel: "All sizes",
      colorLabel: "Color",
      allColorsLabel: "All colors",
      priceLabel: "Price",
      allPricesLabel: "All prices",
      sortLabel: "Sort",
    },
    priceOptions: {
      under5000: "Under Rs. 5,000",
      from5000To7500: "Rs. 5,000 - Rs. 7,500",
      from7500: "Rs. 7,500+",
    },
    sortOptions: {
      newest: "Newest",
      priceAsc: "Price low-high",
      priceDesc: "Price high-low",
    },
    appliedFilterLabels: {
      size: "Size",
      color: "Color",
      price: "Price",
      sort: "Sort",
    },
  },
  product: {
    card: {
      viewAriaLabelPrefix: "View",
      quickLookLabel: "Quick look",
      imageAltSuffix: "styled on a model",
    },
    statusLabel: "New arrival",
    deliveryTitle: "Delivery",
    deliveryText: "Prepaid delivery across India.",
    returnsTitle: "Returns",
    returnsText: "Returns and exchanges follow the store policy.",
    relatedEyebrowFallback: "Keep browsing",
    relatedTitle: "You may also like",
    relatedAction: "Shop all",
    breadcrumbLabel: "Breadcrumb",
    shopBreadcrumbLabel: "Shop",
    notFoundTitle: "Product not found | Neonfold",
    detailSectionLabels: {
      fabric: "Fabric",
      fit: "Fit",
      care: "Care",
      model: "Model",
      measurements: "Measurements",
    },
    gallery: {
      openViewerLabel: "Open image viewer",
      closeViewerLabel: "Close image viewer",
      dialogTitleSuffix: "images",
      imageAltSuffix: "view",
      fullImageAltSuffix: "full image",
      thumbnailLabel: "View image",
    },
    sizeChart: {
      title: "Size chart",
      sizeColumnLabel: "Size",
    },
  },
  search: {
    metadata: {
      title: "Search | Neonfold",
      description: "Search dresses, co-ords, tops, and occasion wear.",
    },
    eyebrow: "Search",
    title: "Find a style.",
    placeholder: "Search dresses, co-ords, tops",
    dialogPlaceholder: "Search dresses, co-ords, colors",
    action: "Search",
    clearAction: "Clear",
    browseAction: "Browse shop",
    emptyTitle: "No styles found.",
    emptyDescription: "Try another search, or browse new arrivals.",
    dialogTitle: "Search products",
    dialogDescription:
      "Search product names, categories, colors, and product notes.",
    editsLabel: "Collections",
    matchingLabel: "Matching styles",
    latestLabel: "Latest styles",
    viewAllAction: "View all",
    resultForLabel: "for",
    resultSingular: "result",
    resultPlural: "results",
    imageAltSuffix: "styled on a model",
  },
} as const;
